version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../logs/nginx:/var/log/nginx
    depends_on:
      - frontend
      - upload-service
      - processing-service
      - events-service

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../infrastructure/docker/frontend/Dockerfile
    environment:
      - NODE_ENV=production

  upload-service:
    build:
      context: ../../backend
      dockerfile: ../infrastructure/docker/upload/Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ../../uploads:/app/uploads
    depends_on:
      - redis

  processing-service:
    build:
      context: ../../backend
      dockerfile: ../infrastructure/docker/processing/Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
      - mongodb

  events-service:
    build:
      context: ../../backend
      dockerfile: ../infrastructure/docker/events/Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-example}

volumes:
  redis_data:
  mongodb_data:
